name: Build and Upload APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK
        id: upload-apk
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk

      - name: Generate Download Link
        id: generate-link
        run: |
          echo "artifact_url=https://github.com/${{ github.repository }}/actions/artifacts/${{ steps.upload-apk.outputs.artifact_id }}" >> $GITHUB_ENV

      - name: Send APK to Slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "channel": "#android-news-reels",
              "text": "The APK is ready! Here is the download link:",
              "attachments": [
                {
                  "text": "Download APK",
                  "title": "app-release.apk",
                  "title_link": "${{ env.artifact_url }}"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
