name: Build and Upload APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  # Changed from 'openjdk' to 'temurin'

      - name: Build with Gradle
        run: ./gradlew assembleRelease  # Build the release APK

      - name: Upload APK
        uses: actions/upload-artifact@v3  # Use v3 for upload
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk  # Uploads any APK in the release folder
